### PR TITLE
missing input option solved, added image and sound file

### LINKED ISSUE #273: Wrong Text / Image
EU Wörter hören: zu Bild Werkzeug wird "ankreuzen" gesprochen
C Wörter hören: Cafe hat falsches Bild (Getränk statt Ort) und wird nicht vorgesprochen, fortsetzen nicht möglich

### PR DESCRIPTION
**Pull request by Mariiiam**
missing input option solved, added image and sound file
fixes #273 #274 

fixed background of HearWords (see #279)

### CODE REVIEW

File: packages/entities/exercise-groups/missing-letter.ts [hunk 1]
```diff
@@ -38,13 +38,21 @@ export class MissingLetter extends AbstractExerciseGroup {
...
+                ? 2
+                : word.length === 3 && this.props.difficulty < 0.6
+                  ? 2
+                  : this.props.difficulty < 0.6
+                    ? 3
+                    : word.length === 4 && this.props.difficulty < 0.8
+                      ? 3
+                      : this.props.difficulty < 0.8
+                        ? 4
+                        : wordLetters.length - 1;
```
Comment (Knorrke) [inline packages/entities/exercise-groups/missing-letter.ts]: This code is hard to understand, maybe we can refactor it. E.g. something like 
```javascript
const numberMissing = 
  this.props.difficulty >= 0.8
    ? wordLetters.length -1
    : Math.min(wordLetters.length - 1, Math.ceil(this.props.difficulty*5)) 
```
or maybe extract the old code into a function `getMissingByDifficulty(difficulty)` and then write:
```javascript
const numberMissing = Math.min(wordLetters.length - 1, getMissingByDifficulty(this.props.difficulty)) 
```

**Comment by Knorrke** [comment]
Thanks for the changes @Mariiiam :-) I found out where to place the `min-Height` argument, so I added that instead of the `worldLetters.length - 1` approach.
@inyono maybe you want to review this, since I added some changes
